name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.47.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
